site_name: 'myservice'

nav:
  - Home: index.md
  - Configuration: configuration.md

theme:
    feaures:
      - tabs
    name: material
    icon:
      logo: material/cloud
    font:
      text: Ubuntu
      code: Ubuntu Mono
